### PR TITLE
Open links in new browser window

### LINKED ISSUE #197: Workflowy Won't Load
I have attempted to install Workflowy as an app, but it will not install. If I use the pre-installed app, it tells me that the page does not exist (the app is directing towards the wrong url), and the "Home" link does not do anything. If I try to install it as a custom app, it just tells me that the page will not load. I am attempting this on a Mac, if that makes any difference.

### PR DESCRIPTION
**Pull request by viktor44**
* Added or restored open link behaviour:
      _Now `Ctrl+Click` (MacOS `Cmd+Click`) opens the link in default browser, `Shift+Click` opens link in default browser in the background._
* Fixed Microsoft Teams app #222 #80 
* Fixed Microsoft Office 365 app #176 
* Fixed #197

### CODE REVIEW

File: app/services/services/tab-webcontents/main.ts [hunk 1]
```diff
@@ -212,35 +213,49 @@ export class TabWebContentsServiceImpl extends TabWebContentsService implements
...
+        //     if (newWindowUrl.startsWith('about:blank')) {
+        //       // if popup is still blank after 2 seconds, we show it to let it finish
+        //       guest.show();
+        //     } else {
+        //       guest.close();
+        //       // otherwise dispatch the current URL of the guest window into our URLRouter
+        //       await provider.dispatchUrl(newWindowUrl, wc.id);
+        //     }
+        //   }
+        // }
```
Comment (magne4000) [inline app/services/services/tab-webcontents/main.ts:250]: I don't remembder the exact issue, but clicking on a PDF file on a thread of mails wasn't working as expected in Station (it did nothing I think)

Comment (viktor44) [reply app/services/services/tab-webcontents/main.ts:250]: yes. Now I see the problem. Previous hack doesn't work now.
I'll create an issue, so we won't lose it.
